#!/bin/bash

find . -type f \( -name ".env" -o -name "db-connector.mjs" \) -exec sed -i \
    -e "s/host: 'localhost'/host: 'classmysql.engr.oregonstate.edu'/g" \
    -e "s/user: 'root'/user: 'capstone_2023_securepass1'/g" \
    -e "s/password: 'DemoDatabasePassword!!123'/password: 'zxob8b@T8!yF'/g" \
    -e "s/dbpassphrase=DemoDatabasePassword!!123/dbpassphrase=zxob8b@T8!yF/g" \
    -e "s/host=localhost/host=classmysql.engr.oregonstate.edu/g" \
    -e "s/dbuser=root/dbuser=capstone_2023_securepass1/g" {} \;

echo "Replacement complete."
