version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: DemoDatabasePassword!!123
      MYSQL_DATABASE: capstone_2023_securepass1
      MYSQL_USER: Demo
      MYSQL_PASSWORD: DemoDatabasePassword!!123
    volumes:
      - mysqldata:/var/lib/mysql
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    networks:
      - safenet
    healthcheck:
      test: ["CMD", "dockerize", "-wait", "tcp://db:3306", "-timeout", "20s"]

  middleware:
    build:
      context: ./application-microservices/middlewares
    volumes:
      - middleware_data:/usr/src/app
    command: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm start"
    networks:
      - safenet
    depends_on:
      - db

  jwt:
    build:
      context: ./application-microservices/jwt-microservice
    depends_on:
      - db  
    env_file:
      - ./application-microservices/jwt-microservice/.env
    networks:
      - safenet
    command: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm start"

  twofac:
    build:
      context: ./application-microservices/two-factor-authentication-code-microservice
    depends_on:
      - middleware
      - db
      - backend
    env_file:
      - ./application-microservices/two-factor-authentication-code-microservice/.env
    volumes:
      - middleware_data:/usr/src/middlewares
    networks:
      - safenet
    command: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm start"

  backend:
    build:
      context: ./application-backend
    depends_on:
      - middleware
      - db
    env_file:
      - ./application-backend/.env
    volumes:
      - middleware_data:/usr/src/application-microservices/middlewares
    networks:
      - safenet
    command: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm start"

  decrypt:
    build:
      context: ./application-microservices/data-decryption-microservice
    depends_on:
      - db
    env_file:
      - ./application-microservices/data-decryption-microservice/.env
    networks:
      - safenet
    command: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm start"

  encrypt:
    build:
      context: ./application-microservices/data-encryption-microservice
    depends_on:
      - db
    env_file:
      - ./application-microservices/data-encryption-microservice/.env
    networks:
      - safenet
    command: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm start"

  frontend:
    build:
      context: ./application-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - db
      - twofac
    env_file:
      - ./application-frontend/.env
    networks:
      - safenet
    command: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm start"

  login:
    build:
      context: ./application-microservices/user-login-microservice/
    depends_on:
      - backend
      - middleware
      - db
      - jwt
      - frontend
    env_file:
      - ./application-microservices/user-login-microservice/.env
    volumes:
      - middleware_data:/usr/src/middlewares
    networks:
      - safenet
    command: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm start"

networks:
  safenet:
    driver: bridge
volumes:
  mysqldata:
  middleware_data:

