#!/bin/bash

killall node && killall node-20

cd ./application-backend/ && npm start &
cd ./application-microservices/data-encryption-microservice/ && npm start &
cd ./application-microservices/data-decryption-microservice/ && npm start &
cd ./application-frontend/ && npm start &
cd ./application-microservices/user-login-microservice/ && npm start &
cd ./application-microservices/jwt-microservice/ && npm start &
cd ./application-microservices/two-factor-authentication-code-microservice/ && npm start &
